### PR TITLE
ICMP PING plugins for Linux and Windows

### PR DESCRIPTION
**Pull request by kruzda**
Now with min, max, average and even packet loss metrics

### CODE REVIEW

**Comment by rphillips** [comment]
Could you add a header for the metrics that are returned? 

Example: https://github.com/racker/rackspace-monitoring-agent-plugins-contrib/blob/master/check_openmanage.sh#L28

**Comment by kruzda** [comment]
Should be good, let me know if it needs anything else

**Comment by kruzda** [comment]
Added example Alarm criteria for them

**Comment by rphillips** [comment]
nice! thanks.

**Pull request merged**
