### PR TITLE
ping scripts act more like ping checks (1 ping / 2 seconds)

### PR DESCRIPTION
**Pull request by kruzda**
implements attributes to configure the number of pings per check and the interval between them (defaults to 5 pings with 2 second intervals)
these defaults would be the same as they are in the vanilla (external) Ping checks currently

### CODE REVIEW

**Comment by kruzda** [comment]
hey guys, any chance of this being pulled?

**Comment by kruzda** [comment]
anybody in there? :)

**Comment by jjbuchan** [comment]
Yep, looks good!  Thanks

+1

**Comment by kruzda** [comment]
Cheers!

**Pull request merged**
