### PR TITLE
varnish_metrics.sh

### PR DESCRIPTION
**Pull request by joeashcraft**
I created a separate varnish plugin to simply output all the varnishstat's we can find, as well as 1 derived from from varnishstat and 1 derived from varnishadm.
"status" metric refers to varnish's running status, not the status of the plugin.

### CODE REVIEW

**Comment by simonvetter** [comment]
you may want to squash all these commits.

**Comment by joeashcraft** [comment]
TIL about rebase and squashing commits!

I'll figure this out and squash 'em in to one.

**Comment by kaustavha** [comment]
```
git rebase -i master
```

**Comment by kaustavha** [comment]
Duplicate of https://github.com/racker/rackspace-monitoring-agent-plugins-contrib/blob/master/varnish.sh
closing.

**Pull request closed without merging**
